import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  cloud: [
    {
      type: "category",
      label: "New to Statsig?",
      collapsed: false,
      collapsible: false,
      items: [
        {
          type: "doc",
          id: "getting-started",
          label: "Overview",
          className: "doc-icon sidebar-icon",
        },

        {
          type: "category",
          label: "Core Concepts",
          collapsed: true,
          className: "lightbulb-icon sidebar-icon",
          items: [
            "understanding-platform",
            "guides/featureflags-or-experiments",

            {
              type: "category",
              label: "Enterprise Topics",
              collapsed: true,
              items: [
                "guides/experimentation-program",
                "guides/running-a-poc",
                "guides/production",
              ]
            },
          ],
        },
        {
          type: "category",
          label: "Data & Metrics",
          className: "data-icon sidebar-icon",
          items: [
            {
              "Metrics 101 - Overview": [
                "metrics/101",
                "metrics/how-metrics-work",
                "metrics/raw-events",
                {
                  type: "category",
                  label: "Auto-generated Metrics",
                  link: {
                    type: "doc",
                    id: "metrics/raw-event-metrics",
                  },
                  items: ["metrics/deprecate-event-dau"],
                },
                "metrics/custom-metrics",
                "metrics/precomputed-metrics",
                "metrics/user-dimensions",
                "metrics/metric-dimensions",
              ],
            },
            // other
            "metrics/ingest",
            "metrics/pulse",
            "metrics/local-metrics",
            "metrics/console",
            "metrics/health-checks",

            // 201
            "metrics/create",
            "metrics/custom-dau",
            "metrics/archiving-metrics",
            "metrics/create-metric-tags",
            "metrics/rollout-alerts",
            "metrics/user",
            "metrics/directionality",

            // 301
            "metrics/create-user-funnels",
            "metrics/verified",
            "metrics/autogenerated",
          ],
        },
        {
          type: "doc",
          id: "faq",
          className: "question-icon sidebar-icon",
        },
      ],
    },
    {
      type: "category",
      label: "Products",
      collapsed: false,
      collapsible: false,
      items: [
        {
          type: "category",
          label: "Feature Flags",
          className: "feature-icon sidebar-icon",
          items: [
            {
              type: "category",
              label: "Feature Flags",
              items: [
                "feature-flags/working-with",
                "feature-flags/create-new",
                "feature-flags/add-rule",
                "feature-flags/test-gate",
                "feature-flags/overrides",
                "feature-flags/scheduled-rollouts",
                "feature-flags/conditions",
                "feature-flags/view-exposures",
                "feature-flags/feature-flags-lifecycle",
                "feature-flags/permanent-and-stale-gates",
                "feature-flags/best-practices",
              ],
            },
            {
              type: "category",
              label: "Dynamic Config",
              items: [
                "dynamic-config/introduction",
                "dynamic-config/working-with",
                "dynamic-config/enforce-schema",
                "dynamic-config/create-new",
                "dynamic-config/add-rule",
                "guides/first-dynamic-config",
              ],
            },
            {
              type: "category",
              label: "Segments",
              items: [
                "segments/introduction",
                "segments/create-new",
                "segments/add-rule",
                "segments/add-id-list",
                "segments/use-segment",
              ],
            },
            {
              type: "category",
              label: "Release Pipeline (Beta)",
              items: [
                "release-pipeline/overview",
                "release-pipeline/create-and-manage",
                "release-pipeline/trigger",
                "release-pipeline/actions",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Experimentation",
          className: "xp-icon sidebar-icon",
          items: [
            "experiments-plus/introduction",
            {
              type: "category",
              label: "Create & Implement",
              items: [
                "experiments-plus/create-new",
                "experiments-plus/power-analysis",
                "experiments-plus/implement",
                "experiments-plus/overrides",
                "experiments-plus/getting-group",
                "experiments-plus/monitor",
                "experiments/quality-score",
              ],
            },
            {
              type: "category",
              label: "Configure Stats Methods",
              items: [
                {
                  type: "category",
                  label: "Experiment Types",
                  items: [
                    "experiments-plus/switchback-tests",
                    "stats-engine/methodologies/one-sided-test",
                    "ai-ml/ai-prompt-experiment",
                    "guides/aa-test",
                  ],
                },
                {
                  type: "category",
                  label: "Reducing False Positives",
                  items: [
                    "stats-engine/methodologies/bonferroni-correction",
                    "stats-engine/methodologies/benjamini–hochberg-procedure",
                  ],
                },
                {
                  type: "category",
                  label: "Health Checks",
                  items: [
                    "stats-engine/methodologies/srm-checks",
                    "stats-engine/pre-experiment-bias",
                  ],
                },
                {
                  type: "category",
                  label: "Variance Reduction",
                  items: [
                    "stats-engine/variance-reduction",
                    "stats-engine/methodologies/cuped",
                    "stats-engine/methodologies/winsorization",
                  ],
                },
                {
                  type: "category",
                  label: "How we Calculate:",
                  items: [
                    "stats-engine/confidence-intervals",
                    "stats-engine/p-value",
                    "stats-engine/metric-deltas",
                    "stats-engine/variance",
                    "stats-engine/methodologies/delta-method",
                    "experiments-plus/bots",
                  ],
                },
                "experiments-plus/stratified-sampling",
                "experiments-plus/sequential-testing",
                "experiments-plus/bayesian",
              ],
            },
            {
              type: "category",
              label: "Reading Experiment Results",
              items: [
                "pulse/read-pulse",
                "pulse/userproperties",
                "pulse/drill-down",
                "pulse/export",
                "pulse/best-practices",
                "experiments-plus/reconciling-experiment-results",
                "pulse/faq",
              ],
            },
            {
              type: "category",
              label: "Further Analysis",
              items: [
                "pulse/custom-queries",
                "insights/aggregated-impact",
                "stats-engine/topline-impact",
                "experiments/meta-analysis",
                "experiments-plus/differential-impact-detection",
                "experiments-plus/interaction-detection",
              ],
            },
            {
              type: "category",
              label: "Ending An Experiment",
              items: [
                "experiments-plus/ending-experiment",
                "experiments-plus/make-decision",
                "experiments-plus/stop-assignments",
                "experiments-plus/conclude-experiment-defer-decision",
                "experiments-plus/abandon",
                "experiments-plus/disable-group",
              ],
            },
            "layers/introduction",
            "holdouts/introduction",
            {
              type: "category",
              label: "Bandit Experiments",
              link: {
                type: "doc",
                id: "autotune/bandit-introduction",
              },
              items: [
                {
                  type: "category",
                  label: "Contextual (CMAB)",
                  link: {
                    type: "doc",
                    id: "autotune/contextual/introduction",
                  },
                  items: [
                    "autotune/contextual/getting-started",
                    "autotune/contextual/monitoring",
                  ],
                },
                {
                  type: "category",
                  label: "Autotune (MAB)",
                  link: {
                    type: "doc",
                    id: "autotune/introduction",
                  },
                  items: [
                    "autotune/setup",
                    "autotune/monitoring",
                    "autotune/multi-armed-bandit",
                  ],
                },
                "autotune/bandit-faq",
                "autotune/using-bandits",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Low-Code Experiments",
          className: "layer-icon sidebar-icon",
          items: [
            "guides/sidecar-experiments/introduction",
            "guides/sidecar-experiments/setup",
            "guides/sidecar-experiments/creating-experiments",
            "guides/sidecar-experiments/measuring-experiments",
            "guides/sidecar-experiments/advanced-configurations",
            "guides/sidecar-experiments/publishing-experiments",
            "guides/sidecar-experiments/integrating-gtm",
            "guides/aa-sidecar",
          ],
        },
        {
          type: "category",
          label: "Product Analytics",
          className: "chart-icon sidebar-icon",
          items: [
            "product-analytics/overview",
            {
              type: "category",
              label: "Metric Explorer",
              items: [
                "product-analytics/drilldown",
                "product-analytics/funnels",
                "product-analytics/retention",
                "product-analytics/distribution",
                "product-analytics/user-journeys",
              ],
            },
            "product-analytics/dashboards",
            {
              type: "category",
              label: "Users",
              items: ["users/introduction", "users/user-profiles"],
            },
            {
              type: "category",
              label: "Alerts",
              items: [
                "product-analytics/alerts",
                "product-analytics/rollout_alerts",
                "product-analytics/topline_alerts",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Web Analytics",
          className: "web-icon sidebar-icon",
          items: ["webanalytics/overview"],
        },
        {
          type: "category",
          label: "Session Replay",
          className: "play-icon sidebar-icon",
          items: [
            "session-replay/overview",
            "session-replay/install",
            "session-replay/configure",
            "session-replay/watch",
          ],
        }
      ],
    },
    {
      type: "category",
      label: "Management & Admin",
      collapsed: false,
      collapsible: false,
      items: [
        {
          className: "team-icon sidebar-icon",
          type: "category",
          label: "Workspace Management",
          items: [
            "access-management/introduction",
            "sdk-keys/api-keys",
            {
              Workspace: [
                "access-management/organizations",
                "access-management/projects",
                "access-management/teams",
              ],
            },
            {
              type: "category",
              label: "Access Management",
              items: [
                {
                  "Single Sign-On": [
                    "access-management/sso/overview",
                    "access-management/sso/okta_sso",
                    "access-management/sso/azuread",
                    "access-management/sso/google",
                  ],
                },
                {
                  type: "category",
                  label: "SCIM User Provisioning",
                  items: [
                    "access-management/scim/overview",
                    "access-management/scim/concepts",

                    {
                      type: "category",
                      label: "Okta Guide",
                      items: [
                        "access-management/scim/okta_scim_setup",
                        "access-management/scim/okta_scim_user_management",
                        "access-management/scim/okta_scim_org_roles",
                        "access-management/scim/okta_scim_team_management",
                        "access-management/scim/okta_scim_troubleshooting",
                      ],
                    },
                    "access-management/scim/scim-endpoints",
                  ],
                },
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Integrations",
          className: "integrations-icon sidebar-icon",
          items: [
            "integrations/introduction",
            {
              "Data Into Statsig": [
                {
                  "Data Connectors": [
                    "integrations/data-connectors/amplitude",
                    "integrations/data-connectors/braze",
                    "integrations/data-connectors/census",
                    "integrations/data-connectors/fivetran",
                    "integrations/data-connectors/google-analytics",
                    "integrations/data-connectors/heap",
                    "integrations/data-connectors/hightouch",
                    "integrations/data-connectors/mixpanel",
                    "integrations/data-connectors/mparticle",
                    "integrations/data-connectors/revenuecat",
                    "integrations/data-connectors/rudderstack",
                    "integrations/data-connectors/segment",
                    "integrations/data-connectors/stitch",
                  ],
                },
                {
                  type: "category",
                  label: "Warehouse Ingestion",
                  link: {
                    type: "doc",
                    id: "data-warehouse-ingestion/introduction",
                  },
                  items: [
                    {
                      "Connection Set Up": [
                        "data-warehouse-ingestion/bigquery",
                        "data-warehouse-ingestion/redshift",
                        "data-warehouse-ingestion/snowflake",
                        "data-warehouse-ingestion/databricks",
                        "data-warehouse-ingestion/synapse",
                        "data-warehouse-ingestion/s3",
                        "data-warehouse-ingestion/athena",
                        "data-warehouse-ingestion/faq",
                      ],
                    },
                    "data-warehouse-ingestion/data_mapping",
                  ],
                },
                "integrations/gtm",
                "integrations/event_filtering",
                "integrations/event_webhook",
                "integrations/openai",
                "experiments/statsiglite",
                "guides/statsig-id-resolver",
                {
                  "Data Imports (Deprecated)": [
                    "integrations/data-imports/overview-deprecated",
                    "integrations/data-imports/bigquery-deprecated",
                    "integrations/data-imports/redshift-deprecated",
                    "integrations/data-imports/snowflake-deprecated",
                    "integrations/data-imports/azure_upload-deprecated",
                  ],
                },
              ],
            },

            {
              "Data Exports": ["integrations/data-exports/overview"],
            },
            {
              "Serverless & Edge": [
                "guides/serverless",
                "guides/cdn-edge-testing",
                "integrations/vercel",
                "integrations/cloudflare",
                "integrations/fastly",
                "integrations/akamai",
              ],
            },
            {
              "Slack, VS Code & Productivity": [
                "integrations/github_code_references",
                "integrations/slack",
                "integrations/jira",
                "integrations/vscode",
              ],
            },
            {
              "Email & CMS Systems": [
                "guides/email-campaign-test",
                "guides/contentful",
                "guides/customer-io-email-abtest",
                "guides/sendgrid-email-abtest",
                "guides/cms-integrations",
              ],
            },
            {
              "No-Code Editors": [
                "guides/shopify-ab-test",
                "guides/framer-analytics",
                "guides/webflow-sidecar-ab-test",
              ],
            },
            {
              "Observability & Infra": [
                "integrations/datadog",
                {
                  type: "category",
                  label: "Terraform",
                  link: {
                    type: "doc",
                    id: "integrations/terraform/introduction",
                  },
                  items: [
                    "integrations/terraform/terraform_gate",
                    "integrations/terraform/terraform_experiment",
                  ],
                },
                {
                  type: "category",
                  label: "Datadog Triggers",
                  link: {
                    type: "doc",
                    id: "integrations/triggers/introduction",
                  },
                  items: ["integrations/triggers/datadog"],
                },
              ],
            },

            {
              type: "category",
              label: "Azure AI",
              link: {
                type: "doc",
                id: "azureai/introduction",
              },
              items: [
                "azureai/getting-started",
                "azureai/model-client",
                "azureai/completions",
                "azureai/embeddings",
                "azureai/capturing-metrics",
                "azureai/running-experiments",
              ],
            },
          ],
        },
        {
          className: "template-icon sidebar-icon",
          type: "category",
          label: "Collaboration",
          items: [
            {
              type: "category",
              label: "Templates & Policies",
              items: [
                {
                  type: "category",
                  label: "Organization Policies",
                  link: {
                    type: "doc",
                    id: "org-admin/organization_policies",
                  },
                  items: [
                    "org-admin/experiment_policy",
                    "org-admin/gates_policy",
                  ],
                },
                {
                  type: "category",
                  label: "Templates",
                  link: {
                    type: "doc",
                    id: "templates/templates",
                  },
                  items: [],
                },
              ],
            },
            "access-management/discussions",
            "access-management/tags",
            "guides/setting-up-reviews",
            "guides/config-history",
          ],
        },
        {
          type: "category",
          label: "Privacy",
          className: "admin-icon sidebar-icon",
          link: {
            type: "doc",
            id: "compliance/introduction",
          },
          items: [
            "compliance/user_data_deletion_requests",
            "guides/private-attributes",
          ],
        },
        {
          type: "category",
          label: "Infrastructure Operations",
          className: "infra-icon sidebar-icon",
          link: {
            type: "doc",
            id: "infrastructure/introduction",
          },
          items: [
            {
              "Domains & IP": [
                "infrastructure/statsig_ip_ranges",
                "infrastructure/statsig_domains",
              ],
            },
            {
              type: "category",
              label: "API Proxies",
              link: {
                type: "doc",
                id: "infrastructure/api_proxy/introduction",
              },
              items: [
                "infrastructure/api_proxy/managed-proxy",
                "infrastructure/api_proxy/custom_proxy",
                "server/concepts/forward_proxy",
              ],
            },
            {
              Reliability: [
                "infrastructure/reliability-faq",
                "guides/uptime",
                "infrastructure/monitoring",
              ],
            },
          ],
        },
      ],
    },
  ],
  api: [
    {
      type: "category",
      label: "Get Started",
      collapsed: false,
      collapsible: false,
      items: [
        "sdks/quickstart",
        "guides/first-feature",
        "guides/logging-events",
        "guides/abn-tests",
      ],
    },
    {
      type: "category",
      label: "Dev Concepts",
      collapsed: false,
      collapsible: false,
      items: [
        "sdks/getting-started",
        "sdks/client-vs-server",
        "concepts/user",
        "client/concepts/initialize",
        "sdks/debugging",
      ]
    },
    {
      type: "category",
      label: "Tutorials",
      collapsed: true,
      items: [
        "client/concepts/parameter-stores",
        "guides/first-device-level-experiment",
        "guides/experiment-on-custom-id-types",
        {
          type: "category",
          label: "Developer Staging",
          collapsed: true,
          items: [
            "guides/using-environments",
            "guides/testing",
          ]
        },
        {
          type: "category",
          label: "Migration Guides",
          collapsed: true,
          items: [
            "guides/open-source-script",
            "guides/ui-based-tool"
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Client SDKs",
      collapsed: false,
      collapsible: true,
      items: [
        {
          className: "html-icon sidebar-icon sdk-sidebar-icon",
          type: "doc",
          id: "client/html-snippet",
        },
        {
          className: "js-icon sidebar-icon sdk-sidebar-icon",
          type: "doc",
          id: "client/javascript-sdk",
        },
        {
          className: "react-icon sidebar-icon sdk-sidebar-icon",
          type: "doc",
          id: "client/javascript-mono/ReactUsage",
        },
        {
          className: "next-icon sidebar-icon sdk-sidebar-icon",
          type: "doc",
          id: "client/javascript-mono/nextjs/NextJsUsage",
        },
        {
          className: "android-icon sidebar-icon sdk-sidebar-icon",
          type: "doc",
          id: "client/androidClientSDK",
        },
        {
          className: "ios-icon sidebar-icon sdk-sidebar-icon",
          type: "doc",
          id: "client/iosClientSDK",
        },
        {
          type: "category",
          label: "More Client SDKs",
          collapsed: true,
          items: [
            {
              className: "cpp-icon sidebar-icon sdk-sidebar-icon",
              type: "doc",
              id: "client/cpp-client-sdk",
            },
            {
              className: "flutter-icon sidebar-icon sdk-sidebar-icon",
              type: "doc",
              id: "client/dartSDK",
            },
            {
              className: "dotnet-icon sidebar-icon sdk-sidebar-icon",
              type: "doc",
              id: "client/dotnetSDK",
            },
            {
              className: "expo-icon sidebar-icon sdk-sidebar-icon",
              type: "doc",
              id: "client/javascript-mono/ExpoUsage",
            },
            {
              className: "react-icon sidebar-icon sdk-sidebar-icon",
              type: "doc",
              id: "client/javascript-mono/ReactNativeUsage",
            },
            {
              className: "angular-icon sidebar-icon sdk-sidebar-icon",
              type: "doc",
              id: "client/javascript-mono/AngularUsage",
            },
            {
              className: "roku-icon sidebar-icon sdk-sidebar-icon",
              type: "doc",
              id: "client/rokuSDK",
            },
            {
              className: "unity-icon sidebar-icon sdk-sidebar-icon",
              type: "doc",
              id: "client/unitySDK",
            },
            {
              type: "category",
              label: "On Device Client SDKs",
              items: [
                {
                  type: "category",
                  label: "JavaScript",
                  link: {
                    type: "doc",
                    id: "client/js-on-device-eval-client",
                  },
                  items: [
                    "client/js-device-eval-mono/MigrationFromOldSDK",
                    "client/js-device-eval-mono/UsingSpecsDataAdapter",
                    "client/js-device-eval-mono/ReactNativeUsage",
                  ],
                },
                "client/swiftOnDeviceEvaluationSDK",
                "client/androidOnDeviceEvaluationSDK",
              ],
            },
            {
              type: "category",
              label: "JavaScript - Maintainance Mode",
              items: [
                "client/deprecated/jsClientSDK",
                "client/deprecated/reactSDK",
                "client/deprecated/reactNativeSDK",
                "client/deprecated/reactNativeExpoSDK",
                "client/jsLocalEvaluationSDK",
                "client/javascript-mono/MigrationFromOldJsClient",
                "client/javascript-mono/MigrationFromOldReact",
              ],
            },
          ],
        },
      ],
    },

    {
      type: "category",
      label: "Server SDKs",
      collapsed: false,
      items: [

        {
          className: "node-icon sidebar-icon sdk-sidebar-icon",
          type: "doc",
          id: "server-core/node-core",
        },
        {
          className: "dotnet-icon sidebar-icon sdk-sidebar-icon",
          type: "doc",
          id: "server/dotnetSDK",
        },
        {
          className: "cpp-icon sidebar-icon sdk-sidebar-icon",
          type: "doc",
          id: "server/cppSDK",
        },
        {
          className: "golang-icon sidebar-icon sdk-sidebar-icon",
          type: "doc",
          id: "server/golangSDK",
        },
        {
          className: "java-icon sidebar-icon sdk-sidebar-icon",
          type: "doc",
          id: "server-core/java-core",
        },
        {
          className: "python-icon sidebar-icon sdk-sidebar-icon",
          type: "doc",
          id: "server-core/python-core",
        },
        {
          className: "elixir-icon sidebar-icon sdk-sidebar-icon",
          type: "doc",
          id: "server-core/elixir-core",
        },
        {
          className: "rust-icon sidebar-icon sdk-sidebar-icon",
          type: "doc",
          id: "server-core/rust-core",
        },
        {
          className: "php-icon sidebar-icon sdk-sidebar-icon",
          type: "doc",
          id: "server-core/php-core",
        },
        {
          className: "ruby-icon sidebar-icon sdk-sidebar-icon",
          type: "doc",
          id: "server/rubySDK",
        },

        {
          type: "category",
          label: "Legacy Server SDKs",
          link: {
            type: "doc",
            id: "server-core/legacy-sdks",
          },
          items: [
            {
              className: "node-icon sidebar-icon sdk-sidebar-icon",
              type: "doc",
              id: "server/nodejsServerSDK",
            },
            {
              className: "python-icon sidebar-icon sdk-sidebar-icon",
              type: "doc",
              id: "server/pythonSDK",
            },
            {
              className: "elixir-icon sidebar-icon sdk-sidebar-icon",
              type: "doc",
              id: "server/erlangSDK",
            },
            {
              className: "java-icon sidebar-icon sdk-sidebar-icon",
              type: "doc",
              id: "server/javaSdk",
            },
            {
              className: "rust-icon sidebar-icon sdk-sidebar-icon",
              type: "doc",
              id: "server/rustSDK",
            },
            {
              className: "php-icon sidebar-icon sdk-sidebar-icon",
              type: "doc",
              id: "server/phpSDK",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Advanced Methods",
      collapsed: true,
      items: [
        "http-api",

        {
          type: "category",
          label: "Other Frameworks",
          items: [
            "guides/node-express-feature-flags",
            "guides/node-express-abtests",
            "guides/python-flask-feature-flags",
            "guides/python-flask-abtests",
          ],
        },
        "client/concepts/persistent_assignment",
        "client/concepts/local-eval-adapter",
        "server/concepts/persistent_assignment",
        "server/concepts/data_store",
        "sdk-keys/target-apps",
        "server/deprecation-notices",
      ],
    },
    {
      type: "category",
      label: "Console API",
      collapsed: true,
      items: [
        "console-api/introduction",
        "console-api/autogenerated",
        "console-api/gates",
        "console-api/segments",
        "console-api/dynamic-configs",
        "console-api/experiments",
        "console-api/holdouts",
        "console-api/layers",
        "console-api/users",
        "console-api/metrics",
        "console-api/audit-logs",
        "console-api/exposure-count",
        "console-api/autotunes",
        "console-api/target-apps",
        "console-api/ingestions",
        "console-api/tags",
        "console-api/keys",
        {
          Reports: [
            "console-api/daily-reports",
            "console-api/daily-reports-deprecated",
          ],
        },
        "console-api/usage-billing",
        "console-api/rules",
      ],
    },
    {
      type: "category",
      label: "Statsig CLI",
      collapsed: true,
      items: [
        "siggy/introduction",
        "siggy/commands",
        "siggy/gate-management",
      ],
    },
  ],
  warehouse: [
    {
      type: "category",
      label: "Introduction",
      collapsed: false,
      collapsible: false,
      items: [
        {
          type: "doc",
          id: "statsig-warehouse-native/introduction",
          label: "About Warehouse Native",
        },
        "statsig-warehouse-native/guides/quick-start",
        "statsig-warehouse-native/native-vs-cloud",
      ]
    },
    {
      type: "category",
      label: "Common Topics",
      collapsed: false,
      collapsible: false,
      items: [
        "statsig-warehouse-native/analysis-tools/data-privacy",
        "statsig-warehouse-native/guides/costs",
        "statsig-warehouse-native/guides/best-practices",
      ]
    },
    {
      type: "category",
      label: "Guides",
      collapsed: false,
      collapsible: false,
      items: [
        {
          type: "category",
          label: "POCs & Evaluations",
          collapsed: true,
          items: [
            "statsig-warehouse-native/guides/running_a_poc",
            "statsig-warehouse-native/guides/playground_eval",
            "statsig-warehouse-native/guides/sdks",
            "statsig-warehouse-native/guides/aatest",
            "metrics/different-id",
          ],
        },
        {
          type: "category",
          label: "Debugging",
          items: [
            "statsig-warehouse-native/guides/checklist",
            "statsig-warehouse-native/guides/debugging",
            "statsig-warehouse-native/guides/sql",
          ],
        },

        "statsig-warehouse-native/connecting-your-warehouse/forwarded-data",
      ],
    },
    {
      type: "category",
      label: "Warehouse Integrations",
      collapsed: false,
      items: [
        "statsig-warehouse-native/guides/connect",
        "statsig-warehouse-native/connecting-your-warehouse/snowflake",
        "statsig-warehouse-native/connecting-your-warehouse/athena",
        "statsig-warehouse-native/connecting-your-warehouse/bigquery",
        "statsig-warehouse-native/connecting-your-warehouse/databricks",
        "statsig-warehouse-native/connecting-your-warehouse/redshift",
      ],
    },
    {
      type: "category",
      label: "Data & Semantic Layer",
      collapsed: true,
      items: [
        "statsig-warehouse-native/configuration/data-and-semantic-layer",
        "statsig-warehouse-native/configuration/metric-sources",
        {
          type: "category",
          label: "Metrics",
          link: {
            type: "doc",
            id: "statsig-warehouse-native/configuration/metrics",
          },
          items: [
            "statsig-warehouse-native/metrics/sum",
            "statsig-warehouse-native/metrics/count",
            "statsig-warehouse-native/metrics/count-distinct",
            "statsig-warehouse-native/metrics/unit-count-once",
            "statsig-warehouse-native/metrics/unit-count-window",
            "statsig-warehouse-native/metrics/unit-count-latest",
            "statsig-warehouse-native/metrics/unit-count-rate",
            "statsig-warehouse-native/metrics/mean",
            "statsig-warehouse-native/metrics/ratio",
            "statsig-warehouse-native/metrics/funnel",
            "statsig-warehouse-native/metrics/percentile",
            "statsig-warehouse-native/metrics/log",
            "statsig-warehouse-native/metrics/latest-value",
            "statsig-warehouse-native/metrics/retention",
            "statsig-warehouse-native/metrics/max-min",
          ],
        },
        "statsig-warehouse-native/configuration/metric-examples",
        "statsig-warehouse-native/configuration/dimensional-analysis",
        "statsig-warehouse-native/configuration/assignment-sources",
        "statsig-warehouse-native/configuration/entity-properties",
        "statsig-warehouse-native/configuration/qualifying-events",
        "statsig-warehouse-native/configuration/tags-and-teams",
        "metrics/verified",
        "statsig-warehouse-native/configuration/query-tools",
        {
          type: "category",
          label: "Programmatic Management",
          items: [
            "statsig-warehouse-native/configuration/console-api",
            "statsig-warehouse-native/configuration/semantic-layer-sync",
          ],
        },
        "statsig-warehouse-native/features/roles-and-access",
      ],
    },
    {
      type: "category",
      label: "Experiment Analysis",
      collapsed: true,
      items: [
        "statsig-warehouse-native/features/experiment-options",
        {
          type: "category",
          label: "Setup",
          items: [
            "statsig-warehouse-native/features/configure-an-experiment",
            "statsig-warehouse-native/features/types-of-experiments",
            "statsig-warehouse-native/features/power-analysis",
            "experiments-plus/stratified-sampling-whn",
            "experiments-plus/differential-impact-detection-whn",
            "statsig-warehouse-native/features/targeting",
            "statsig-warehouse-native/features/id-resolution",
            "statsig-warehouse-native/features/filtering-exposures",
            "statsig-warehouse-native/metrics/normalized-metrics",
          ],
        },
        {
          type: "category",
          label: "Loading Results",
          link: {
            type: "doc",
            id: "statsig-warehouse-native/features/reloads",
          },
          items: [
            "statsig-warehouse-native/features/turbo",
            "statsig-warehouse-native/features/full-reloads",
            "statsig-warehouse-native/features/incremental-reloads",
            "statsig-warehouse-native/features/metric-reloads",
            "statsig-warehouse-native/connecting-your-warehouse/scheduled-reloads",
            "statsig-warehouse-native/analysis-tools/pipeline-overview",
            "statsig-warehouse-native/features/freshness",
          ],
        },
        {
          type: "category",
          label: "Interpreting Results",
          items: [
            "statsig-warehouse-native/read-pulse-whn",
            "pulse/drill-down-whn",
            "pulse/custom-queries-whn",
            "pulse/access-whn",
            "pulse/best-practices-whn",
            "pulse/faq-whn",
            "statsig-warehouse-native/features/monitor-an-experiment",
          ],
        },
        {
          type: "category",
          label: "Statistics",
          items: [
            "statsig-warehouse-native/features/statistics",
            "stats-engine/metric-deltas-whn",
            "stats-engine/variance-whn",
            "stats-engine/confidence-intervals-whn",
            "stats-engine/p-value-whn",
            "stats-engine/topline-impact-whn",
            "stats-engine/variance-reduction-whn",
            "stats-engine/pre-experiment-bias-whn",
            {
              "Methodologies Used": [
                "stats-engine/methodologies/bonferroni-correction-whn",
                "stats-engine/methodologies/benjamini–hochberg-procedure-whn",
                "stats-engine/methodologies/cuped-whn",
                "stats-engine/methodologies/delta-method-whn",
                "stats-engine/methodologies/srm-checks-whn",
                "stats-engine/methodologies/winsorization-whn",
                "stats-engine/methodologies/one-sided-test-whn",
              ],
            },
          ],
        },
        "experiments/meta-analysis-whn",
        "insights/aggregated-impact-whn",
        "experiments/quality-score-whn",
        "statsig-warehouse-native/features/reports",
        "statsig-warehouse-native/features/autotune",
        "statsig-warehouse-native/features/use-case",
      ],
    },
    {
      type: "category",
      label: "Other Features",
      collapsed: true,
      items: [
        "statsig-warehouse-native/features/mex-on-warehouse-native",
        {
          type: "category",
          label: "CURE",
          items: [
            "statsig-warehouse-native/cure/introduction",
            "statsig-warehouse-native/cure/cure-setup"],
        },
        {
          type: "category",
          label: "Geotests",
          items: [
            "statsig-warehouse-native/geotests/introduction",
            "statsig-warehouse-native/geotests/geotests-setup",
            "statsig-warehouse-native/geotests/methodology",
          ],
        },
        "statsig-warehouse-native/features/other-useful-features",
      ],
    },
  ]
};

export default sidebars;
