const script = document.createElement("script");
script.src = "https://widget.kapa.ai/kapa-widget.bundle.js";
script.async = true;
script.setAttribute("data-website-id", "418990dd-0615-4ba7-b52f-3ab8c1af4e79");
script.setAttribute("data-project-name", "Statsig");
script.setAttribute("data-project-color", "#202020");
script.setAttribute("data-project-logo", "https://statsig.com/images/sections/multi-products-v2/menu-statsig.svg");
script.setAttribute("data-modal-image", "https://raw.githubusercontent.com/statsig-io/docs/f263b88116852d7c7174b82df1b528609a1ea073/static/img/favicon.svg");
script.setAttribute("data-modal-lock-scroll", "false");
script.setAttribute("data-modal-disclaimer", "Statsig Docs AI answers questions using documentations, API references, blogs, and videos. Responses are AI-generated, and we encourage you to rate them to let us know what you think!");
script.setAttribute("data-answer-feedback-info-text", "All feedback is reviewed by the Statsig team.");
script.setAttribute("data-modal-full-screen-on-mobile", "false");
script.setAttribute("data-kapa-branding-text", "Powered by kapa.ai and Statsig");
script.setAttribute("data-question-text-color", "#1963d2");
document.head.appendChild(script);
