/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Statsig Docs",
  "tagline": "Ship faster!",
  "url": "https://docs.statsig.com",
  "baseUrl": "/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/favicon.svg",
  "organizationName": "statsig",
  "projectName": "statsig-io/docs",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.ts",
          "editUrl": "https://github.com/statsig-io/docs/edit/main/",
          "showLastUpdateTime": true,
          "showLastUpdateAuthor": false,
          "routeBasePath": "/",
          "remarkPlugins": [
            null
          ],
          "rehypePlugins": [
            null
          ]
        },
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "plugins": [
    null,
    [
      "@docusaurus/plugin-client-redirects",
      {
        "redirects": [
          {
            "to": "/guides/feature-flags",
            "from": "/guides/guides/feature-gates"
          },
          {
            "to": "/feature-flags/overview",
            "from": [
              "/feature-gates/overview",
              "/feature-gates",
              "/feature-flags",
              "/feature-gates/working-with",
              "/feature-flags/working-with",
              "/feature-gates/implement",
              "/feature-gates/implement/client",
              "/feature-gates/implement/server",
              "/feature-gates/implement/http-api"
            ]
          },
          {
            "to": "/feature-flags/create",
            "from": [
              "/feature-gates/create-new",
              "/feature-flags/create-new"
            ]
          },
          {
            "to": "/feature-flags/create#add-a-rule-to-your-feature-gate",
            "from": [
              "/feature-gates/add-rule",
              "/feature-flags/add-rule"
            ]
          },
          {
            "to": "/feature-flags/test-gate",
            "from": "/feature-gates/test-gate"
          },
          {
            "to": "/feature-flags/overrides",
            "from": "/feature-gates/overrides"
          },
          {
            "to": "/feature-flags/scheduled-rollouts",
            "from": "/feature-gates/scheduled-rollouts"
          },
          {
            "to": "/feature-flags/conditions",
            "from": "/feature-gates/conditions"
          },
          {
            "to": "/feature-flags/view-exposures",
            "from": "/feature-gates/view-exposures"
          },
          {
            "to": "/feature-flags/feature-flags-lifecycle",
            "from": "/feature-gates/feature-gates-lifecycle"
          },
          {
            "to": "/feature-flags/permanent-and-stale-gates",
            "from": "/feature-gates/permanent-and-stale-gates"
          },
          {
            "to": "/feature-flags/best-practices",
            "from": "/feature-gates/best-practices"
          },
          {
            "to": "/",
            "from": [
              "/feature-flags/implement",
              "/feature-flags/implement/client",
              "/feature-flags/implement/server",
              "/feature-flags/implement/http-api",
              "/category/walkthrough-guides"
            ]
          },
          {
            "to": "/pulse/read-pulse",
            "from": [
              "/experiments-plus/read-results",
              "/pulse"
            ]
          },
          {
            "to": "/experiments-plus/getting-group#rules",
            "from": "/experiments-plus/rules"
          },
          {
            "to": "/experiments-plus",
            "from": "/experiments-plus/working-with"
          },
          {
            "to": "/experiments-plus#why-experiment",
            "from": "/experiments-plus/experimentation/why-experiment"
          },
          {
            "to": "/experiments-plus#scenarios-for-experimentation",
            "from": "/experiments-plus/experimentation/scenarios"
          },
          {
            "to": "/experiments-plus#key-concepts-in-experimentation",
            "from": "/experiments-plus/experimentation/common-terms"
          },
          {
            "to": "/experiments-plus#choosing-the-right-randomization-unit",
            "from": "/experiments-plus/experimentation/choosing-randomization-unit"
          },
          {
            "to": "/experiments-plus/stop-assignments",
            "from": "/experiments-plus/pause-assignment"
          },
          {
            "to": "/product-analytics/overview",
            "from": [
              "/product-analytics",
              "/mex",
              "/mex/overview",
              "/metrics/events-explorer"
            ]
          },
          {
            "to": "/product-analytics/drilldown",
            "from": [
              "/mex/drilldown",
              "/events-explorer"
            ]
          },
          {
            "to": "/product-analytics/dashboards",
            "from": "/mex/dashboards"
          },
          {
            "to": "/product-analytics/funnels",
            "from": "/mex/funnels"
          },
          {
            "to": "/product-analytics/retention",
            "from": "/mex/retention"
          },
          {
            "to": "/product-analytics/alerts/",
            "from": "/metrics/metric-alerts"
          },
          {
            "to": "/client/javascript-sdk",
            "from": [
              "/client/introduction/javascript-sdk",
              "/client/jsClientSDK"
            ]
          },
          {
            "to": "/client/javascript-sdk/react",
            "from": "/client/reactSDK"
          },
          {
            "to": "/client/javascript-sdk/react-native",
            "from": [
              "/client/reactNative",
              "/client/reactNativeSDK"
            ]
          },
          {
            "to": "/client/javascript-sdk/expo",
            "from": "/client/reactNativeExpoSDK"
          },
          {
            "to": "/client/javascript-sdk/next-js",
            "from": [
              "/guides/nextjs-feature-flags",
              "/client/javascript-sdk/next-js-pages-router",
              "/guides/nextjs-page-router-feature-flags",
              "/client/javascript-sdk/next-js-app-router"
            ]
          },
          {
            "to": "/client/javascript-sdk/migrating-from-statsig-js",
            "from": [
              "/js-migration",
              "/js-migration-rn",
              "/js-migration-expo"
            ]
          },
          {
            "to": "/client/javascript-sdk/migrating-from-statsig-react",
            "from": "/js-migration-react"
          },
          {
            "to": "/client/javascript-sdk#layers",
            "from": "/layers/js-tutorial"
          },
          {
            "to": "/client/concepts/initialize",
            "from": [
              "/client/javascript-sdk/react/init-strategies",
              "/client/concepts/bootstrapping"
            ]
          },
          {
            "to": "/concepts/user",
            "from": [
              "/server/concepts/user/",
              "/client/concepts/user/"
            ]
          },
          {
            "to": "/statsig-warehouse-native/configuration/assignment-sources",
            "from": "/statsig-warehouse-native/guides/assignment-sources/"
          },
          {
            "to": "/statsig-warehouse-native/introduction",
            "from": "/guides/experiment-analysis/"
          },
          {
            "to": "/statsig-warehouse-native/introduction",
            "from": "/statsig-warehouse-native"
          },
          {
            "to": "/guides/aa-test#offline-aa-tests",
            "from": "/stats-engine/offlineaa"
          },
          {
            "to": "/console-api/all-endpoints-generated",
            "from": "/console-api/all-endpoints"
          },
          {
            "to": "/aggregated-impact",
            "from": "/insights/"
          },
          {
            "to": "/dynamic-config/working-with",
            "from": "/dynamic-config/implement/"
          },
          {
            "to": "/sdks/getting-started",
            "from": "/sdks/sdks-overview"
          },
          {
            "to": "/sdk/debugging",
            "from": "/debugging"
          },
          {
            "to": "/concepts/user#why-is-an-id-always-required-for-server-sdks",
            "from": "/messages/serverRequiredUserID/"
          },
          {
            "to": "/guides/sidecar-experiments/introduction",
            "from": "/guides/landing-page-experiments"
          },
          {
            "to": "/integrations/terraform/introduction",
            "from": "/integrations/terraform"
          },
          {
            "to": "/ai-evals/overview",
            "from": [
              "/ai-configs",
              "/prompts",
              "/aievals",
              "/ai-evals",
              "/ai-ml/ai-prompt-experiment"
            ]
          },
          {
            "to": "/webanalytics/autocapture/",
            "from": "/client/concepts/autocapture/"
          },
          {
            "to": "/integrations/introduction",
            "from": "/integrations/vscode"
          },
          {
            "to": "/experiments-plus/bayesian/",
            "from": "/experiments-plus/bayesian-deprecated/"
          },
          {
            "to": "/product-analytics/alerts/topline_alerts",
            "from": "/product-analytics/topline_alerts"
          }
        ]
      }
    ]
  ],
  "themes": [],
  "themeConfig": {
    "image": "img/docs_meta_q3_2023.png",
    "docs": {
      "sidebar": {
        "autoCollapseCategories": false,
        "hideable": false
      },
      "versionPersistence": "localStorage"
    },
    "navbar": {
      "title": "",
      "logo": {
        "alt": "Statsig",
        "src": "img/2025_Statsig_Logo_Black.svg",
        "srcDark": "img/2025_Statsig_Logo_White.svg",
        "href": "/"
      },
      "items": [
        {
          "type": "doc",
          "position": "left",
          "docId": "getting-started",
          "sidebarId": "product-docs",
          "label": "Product Docs",
          "id": "product-docs"
        },
        {
          "type": "docSidebar",
          "position": "left",
          "sidebarId": "warehouse",
          "label": "Warehouse Native",
          "id": "warehouse"
        },
        {
          "type": "docSidebar",
          "position": "left",
          "sidebarId": "api",
          "label": "SDKs & APIs",
          "id": "sdk-api"
        },
        {
          "type": "custom-askAI",
          "position": "right"
        },
        {
          "type": "custom-signupCTA",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Getting Started",
              "to": "/"
            },
            {
              "label": "FAQ",
              "to": "/faq"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "Statsig Home",
              "href": "https://statsig.com"
            },
            {
              "label": "Blog",
              "href": "https://statsig.com/blog"
            },
            {
              "label": "Slack Community",
              "href": "https://statsig.com/slack"
            },
            {
              "label": "Code",
              "href": "https://github.com/statsig-io"
            },
            {
              "label": "Statsig University",
              "href": "https://learn.statsig.com/certifications"
            }
          ]
        }
      ],
      "copyright": "Copyright (c) 2025 Statsig, Inc. | Thanks Docusaurus"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "bash",
        "diff",
        "json",
        "swift",
        "java",
        "ruby",
        "csharp",
        "jsx",
        "go",
        "python",
        "kotlin",
        "erlang",
        "dart",
        "rust",
        "objectivec"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "scripts": [
    {
      "id": "kapa-widget-script",
      "src": "https://widget.kapa.ai/kapa-widget.bundle.js",
      "defer": true,
      "data-website-id": "418990dd-0615-4ba7-b52f-3ab8c1af4e79",
      "data-project-name": "Statsig",
      "data-project-color": "#1963d2",
      "data-project-logo": "https://statsig.com/images/sections/multi-products-v2/menu-statsig.svg",
      "data-scale-factor": "1.2",
      "data-modal-lock-scroll": "false",
      "data-modal-image": "https://raw.githubusercontent.com/statsig-io/docs/f263b88116852d7c7174b82df1b528609a1ea073/static/img/favicon.svg",
      "data-button-hide": "true",
      "data-modal-override-open-id": "ask-ai-navbar-button",
      "data-modal-disclaimer": "Statsig Docs AI answers questions using documentations, API references, blogs, and videos. Responses are AI-generated, and we encourage you to rate them to let us know what you think!",
      "data-answer-feedback-info-text": "All feedback is reviewed by the Statsig team.",
      "data-search-mode-default": "true",
      "data-search-mode-enabled": "true",
      "data-modal-open-on-command-k": "true",
      "data-modal-command-k-search-mode-default": "true",
      "data-modal-search-input-placeholder": "Search Statsig docs...",
      "data-search-include-source-names": "[\"Documentation\"]",
      "data-search-show-ask-ai-cta": "false",
      "data-search-result-link-target": "_self",
      "data-modal-full-screen-on-mobile": "false",
      "data-kapa-branding-text": "Powered by kapa.ai and Statsig",
      "data-question-text-color": "#1963d2"
    }
  ],
  "stylesheets": [
    "https://fonts.googleapis.com/icon?family=Material+Icons",
    {
      "href": "https://cdn.jsdelivr.net/npm/katex@0.13.24/dist/katex.min.css",
      "type": "text/css",
      "integrity": "sha384-odtC+0UGzzFL/6PNoE8rX/SPcQDXBJ+uRepguP4QkPCm2LBxH3FA3y+fKSiJ+AmM",
      "crossorigin": "anonymous"
    }
  ],
  "baseUrlIssueBanner": true,
  "future": {
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "headTags": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  }
};
